apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejs-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nodejs-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.configMapData }}
  {{ $key }}: {{ quote $value | nindent 4 }}
{{- end }}

